server:
  port: 8769
spring:
  application:
    name: service-zuul

eurekaServer:
  host: localhost
  port: 8761
  user: root
  password: root

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka

zuul:
  routes:
    api-org:
      path: /api-org/**
      serviceId: org-portal-service

    #api-b:
      #path: /api-b/**
      #serviceId: service-feign
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:8769/api-org/oauth/token
      user-authorization-uri: http://localhost:8769/api-org/oauth/authorize
      client-id: webApp
      client-secret: webApp
    resource:
      user-info-uri:  http://localhost:8769/api-org/user
      prefer-token-info: false