spring:
  application:
      name: org-portal-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      label: master
      profile: dev
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#      sampler:
#        probability: 1.0

  datasource:
    druid:
      org:
        url: jdbc:mysql://192.168.1.217:3306/yilucaifu_org?useUnicode=true&characterEncoding=UTF-8
        username: root
      #password:
        password: 7ujm8ik,
      juling:
        url: jdbc:mysql://192.168.1.217:3306/juling?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 7ujm8ik,
      driverClassName: com.mysql.jdbc.Driver
      #driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT1FROMDUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j
      logSlowSql: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1,192.168.1.217
        deny: 192.168.32.139 #访问黑名单
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
    type: com.alibaba.druid.pool.DruidDataSource

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000ms
    jedis:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 0
        max-wait: -1ms

  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
  ## 消费端配置
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#配置日志
logging:
  config: classpath:logback-spring.xml
#  path: /logs/org
#  file:
#    max-history: 30
#    max-size: 50MB
  #不同目录下的日志可配置不同级别
#  level:
  #mybatis alibaba log configure
#    org.springframework.security: debug
#    java.sql.ResultSet: info
#    java.sql.Connection: debug
#    java.sql.Statement: debug
#    java.sql.PreparedStatement: debug
#    org.mybatis.spring: debug
#    cn.yilucaifu.mapper: debug

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#设置超时时间3秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
