server.name.url: http://localhost:8080
http.server.url: http://localhost:8080

#信息收集查看人手机号
phone.gatherinfo: 15210732085lll


# Redis
redisKey:
  # 缓存时间 默认半小时
  prefix:
    # 用户登录信息前缀
    user_info: 'USER_INFO:'
    # 验证码Redis前缀
    verifycode: 'VERIFYCODE:'

jwt:
  #jwt对称加密签名密钥
  secret: xiaodong2018@yilucaifu
  #jwt生成token时效一天
  expires: 86400
